{
  "formatVersion": "1.1",
  "component": {
    "group": "purplecreate.tramways",
    "module": "tramways-forge",
    "version": "0.2.2-mc1.20.1-forge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tramways-forge-0.2.2-mc1.20.1-forge.jar",
          "url": "tramways-forge-0.2.2-mc1.20.1-forge.jar",
          "size": 807247,
          "sha512": "b7f0c4895d4d8f5c398c3a0735dc4ca0a6e337390d331c89c15c172e41a4936b36ddb515132da6c788e64ea4cf45997f998bdc422d52c58e29b8a761f5da8851",
          "sha256": "ce62bfbdf6c1ac9a6025e766c6259749b4ef510e17fa6cfd7eb4bb3493863056",
          "sha1": "ee0af9925a8e273a12e0f169652fce2b6fd0facc",
          "md5": "e8fe1b9edcbebaebce743613bc4b30aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.3.5"
          }
        },
        {
          "group": "javazoom",
          "module": "jlayer",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "0.5.1.j-55"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.20-1.3.3"
          }
        },
        {
          "group": "com.jozufozu.flywheel",
          "module": "flywheel-forge-1.20.1",
          "version": {
            "requires": "0.6.11-13"
          }
        }
      ],
      "files": [
        {
          "name": "tramways-forge-0.2.2-mc1.20.1-forge.jar",
          "url": "tramways-forge-0.2.2-mc1.20.1-forge.jar",
          "size": 807247,
          "sha512": "b7f0c4895d4d8f5c398c3a0735dc4ca0a6e337390d331c89c15c172e41a4936b36ddb515132da6c788e64ea4cf45997f998bdc422d52c58e29b8a761f5da8851",
          "sha256": "ce62bfbdf6c1ac9a6025e766c6259749b4ef510e17fa6cfd7eb4bb3493863056",
          "sha1": "ee0af9925a8e273a12e0f169652fce2b6fd0facc",
          "md5": "e8fe1b9edcbebaebce743613bc4b30aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tramways-forge-0.2.2-mc1.20.1-forge-sources.jar",
          "url": "tramways-forge-0.2.2-mc1.20.1-forge-sources.jar",
          "size": 392474,
          "sha512": "fc53f52408c30082f57ad92754a8d9e0d26f22a596869c341f3e88929696d174a54a277f62020b0c2bba5dfbd63d8b5d3168728cda463e85a6ab58ff3453d780",
          "sha256": "b20dcebcae1f2614bdb7dad5c73f37d026174a2ed1d1f910025f61068318c01b",
          "sha1": "06d9d1ea928f3fb2aebda03e0aa5cf7debe00e74",
          "md5": "0d51ac4e05c1216740eb470951fbca00"
        }
      ]
    }
  ]
}
