{
  "formatVersion": "1.1",
  "component": {
    "group": "purplecreate.tramways",
    "module": "tramways-forge",
    "version": "0.2.1-mc1.20.1-forge-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tramways-forge-0.2.1-mc1.20.1-forge-1.jar",
          "url": "tramways-forge-0.2.1-mc1.20.1-forge-1.jar",
          "size": 807200,
          "sha512": "bef91efa755068f33042715dbf1aa2920b2e3e47298c5a1e52a5f42bc50a00299511416ececd0880287279b1f1750597c482d37d2c07c7866838b41e42ba0c33",
          "sha256": "ab0cd6986ef90946dacfd022a8de0a291ed1d8ca40eaa6d63298ff74684a8d73",
          "sha1": "751958201db741c03506737c6c60f375842d9ebf",
          "md5": "e8c2d027fb10ff8519a3f2d9d1119b8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.3.5"
          }
        },
        {
          "group": "javazoom",
          "module": "jlayer",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "0.5.1.j-55"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.20-1.3.3"
          }
        },
        {
          "group": "com.jozufozu.flywheel",
          "module": "flywheel-forge-1.20.1",
          "version": {
            "requires": "0.6.11-13"
          }
        }
      ],
      "files": [
        {
          "name": "tramways-forge-0.2.1-mc1.20.1-forge-1.jar",
          "url": "tramways-forge-0.2.1-mc1.20.1-forge-1.jar",
          "size": 807200,
          "sha512": "bef91efa755068f33042715dbf1aa2920b2e3e47298c5a1e52a5f42bc50a00299511416ececd0880287279b1f1750597c482d37d2c07c7866838b41e42ba0c33",
          "sha256": "ab0cd6986ef90946dacfd022a8de0a291ed1d8ca40eaa6d63298ff74684a8d73",
          "sha1": "751958201db741c03506737c6c60f375842d9ebf",
          "md5": "e8c2d027fb10ff8519a3f2d9d1119b8f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tramways-forge-0.2.1-mc1.20.1-forge-1-sources.jar",
          "url": "tramways-forge-0.2.1-mc1.20.1-forge-1-sources.jar",
          "size": 392455,
          "sha512": "2b6e171863f888c57a2a9b0ca0fae5436fb8cab3150c378726d81a6c172022e4f32724896a771e195f7f5ef6b19bb1429d70193cf4bffee9122a43d2f10b9870",
          "sha256": "5eb53550c3ec9ee9f88bc4494580290054d739e84baeb96448398c8ec3013515",
          "sha1": "ade6b1beaa1692a3c367cf931e051dac379a20cc",
          "md5": "d61457632e4939570f573578b9945aa3"
        }
      ]
    }
  ]
}
