{
  "formatVersion": "1.1",
  "component": {
    "group": "purplecreate.tramways",
    "module": "tramways-forge",
    "version": "0.3.3-mc1.20.1-forge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tramways-forge-0.3.3-mc1.20.1-forge.jar",
          "url": "tramways-forge-0.3.3-mc1.20.1-forge.jar",
          "size": 814425,
          "sha512": "b1a8d2286752a56b4ac3651e2ce36c9d0ea9b380f72535b20370678e37b7fd2db33b82d1e90d205195b8dc613f9f07b138a6156b52b993e4b6866998ad6848a4",
          "sha256": "82a65903b9b3331463cb3c7dc1a054527ed713185fc21e4f251a41d4ad5d210b",
          "sha1": "c0d3682accd1f12ea5277f4cdbff32d7bfd988a9",
          "md5": "7eb2579dbbf7c835afc3c3c24bf301c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.3.5"
          }
        },
        {
          "group": "javazoom",
          "module": "jlayer",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.8-289"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.20-1.3.3"
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Forge-1.20.1",
          "version": {
            "requires": "1.0.91"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-forge-1.20.1",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "tramways-forge-0.3.3-mc1.20.1-forge.jar",
          "url": "tramways-forge-0.3.3-mc1.20.1-forge.jar",
          "size": 814425,
          "sha512": "b1a8d2286752a56b4ac3651e2ce36c9d0ea9b380f72535b20370678e37b7fd2db33b82d1e90d205195b8dc613f9f07b138a6156b52b993e4b6866998ad6848a4",
          "sha256": "82a65903b9b3331463cb3c7dc1a054527ed713185fc21e4f251a41d4ad5d210b",
          "sha1": "c0d3682accd1f12ea5277f4cdbff32d7bfd988a9",
          "md5": "7eb2579dbbf7c835afc3c3c24bf301c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tramways-forge-0.3.3-mc1.20.1-forge-sources.jar",
          "url": "tramways-forge-0.3.3-mc1.20.1-forge-sources.jar",
          "size": 399957,
          "sha512": "5d59684f36a71c439e8c8f8ff7d02ebd1cb5a1fd3bcf473f1c28971f99beecd37bb0da66dc01dbe696400d29f8f6cfd3038359cf9cc74ce8a8f3fb3fcd9d2ed5",
          "sha256": "be3d9d5467223a1c4f9d9312072f54f4e25cb45d1a5640869efc5e0bf82d008e",
          "sha1": "1ef76eabe4b0bdf2b1b38950e77dd6cbfca91a13",
          "md5": "fed2b1153290fddc7233ca58794e7c52"
        }
      ]
    }
  ]
}
