{
  "formatVersion": "1.1",
  "component": {
    "group": "purplecreate.tramways",
    "module": "tramways-forge",
    "version": "0.3.1-mc1.20.1-forge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tramways-forge-0.3.1-mc1.20.1-forge.jar",
          "url": "tramways-forge-0.3.1-mc1.20.1-forge.jar",
          "size": 812449,
          "sha512": "9445ed4af84e13c800059e479c7e2f1a4d0f85521b33562df45617831c9d6cb4a69ce9ad187701efbcdb6bc20ed74bf894b515baa3976990b1e64fb774c1b640",
          "sha256": "306650ee3d622621076fb564c78242b098e0eb700742c0a1caaa4a50c70f48e7",
          "sha1": "5d9437ff8891fcd2cc978a3c11c7a5f0103cc9dc",
          "md5": "1182b4f7617c1b0efcebbe4fa86d5d0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.3.5"
          }
        },
        {
          "group": "javazoom",
          "module": "jlayer",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.6-150"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.20-1.3.3"
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Forge-1.20.1",
          "version": {
            "requires": "1.0.80"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-forge-1.20.1",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "tramways-forge-0.3.1-mc1.20.1-forge.jar",
          "url": "tramways-forge-0.3.1-mc1.20.1-forge.jar",
          "size": 812449,
          "sha512": "9445ed4af84e13c800059e479c7e2f1a4d0f85521b33562df45617831c9d6cb4a69ce9ad187701efbcdb6bc20ed74bf894b515baa3976990b1e64fb774c1b640",
          "sha256": "306650ee3d622621076fb564c78242b098e0eb700742c0a1caaa4a50c70f48e7",
          "sha1": "5d9437ff8891fcd2cc978a3c11c7a5f0103cc9dc",
          "md5": "1182b4f7617c1b0efcebbe4fa86d5d0c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tramways-forge-0.3.1-mc1.20.1-forge-sources.jar",
          "url": "tramways-forge-0.3.1-mc1.20.1-forge-sources.jar",
          "size": 398896,
          "sha512": "b7faac064ab985dab99d474253d4ad2057d9dddbdb3467f3425c0b0cb938a5841a817d7e104137ac88b7742e9044e820bf35c6e6eb6893ff09692b93791b0958",
          "sha256": "5e4b6ee816f5ef5c0d3c4741053bad01c415c5b2d9af43b29224c70fdd8b7f8b",
          "sha1": "c1a3d412d2acc66b8aef32b6e120cf03b6f875cc",
          "md5": "f2c53331e9c4d31c6da3fb17881f04f6"
        }
      ]
    }
  ]
}
