{
  "formatVersion": "1.1",
  "component": {
    "group": "purplecreate.tramways",
    "module": "tramways-common",
    "version": "0.3.2-next-1-mc1.20.1-common",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tramways-common-0.3.2-next-1-mc1.20.1-common.jar",
          "url": "tramways-common-0.3.2-next-1-mc1.20.1-common.jar",
          "size": 353029,
          "sha512": "13149c9def98aae6d53c29f8e1f496b4eadf9ed157c1b9806f931ea07a497181ba09daf67979a97124d1dc5001e4a2fa6c9f64a3c1a47fa91629df5d47439986",
          "sha256": "8acddaea7da3383be558bb232cf21f10b1b65ee8dc93f0246e5a54b9b43b8006",
          "sha1": "29756078e8f0ebcc53ec3f6e0232fbcfa0044347",
          "md5": "d668ad2820fca23a0f6bbb06ed3cf2d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javazoom",
          "module": "jlayer",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-common",
          "version": {
            "requires": "0.3.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "tramways-common-0.3.2-next-1-mc1.20.1-common.jar",
          "url": "tramways-common-0.3.2-next-1-mc1.20.1-common.jar",
          "size": 353029,
          "sha512": "13149c9def98aae6d53c29f8e1f496b4eadf9ed157c1b9806f931ea07a497181ba09daf67979a97124d1dc5001e4a2fa6c9f64a3c1a47fa91629df5d47439986",
          "sha256": "8acddaea7da3383be558bb232cf21f10b1b65ee8dc93f0246e5a54b9b43b8006",
          "sha1": "29756078e8f0ebcc53ec3f6e0232fbcfa0044347",
          "md5": "d668ad2820fca23a0f6bbb06ed3cf2d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tramways-common-0.3.2-next-1-mc1.20.1-common-sources.jar",
          "url": "tramways-common-0.3.2-next-1-mc1.20.1-common-sources.jar",
          "size": 244998,
          "sha512": "8a5d5a39199e3f3a9125e56ded65e7cd23660fca74c0646c4a9988f23522bc4cb85f0039faf3af441a024636e64ca7e51fc204ab12196b8a8b37e6a7ec84b43e",
          "sha256": "8d7882bbbe18a2e6510764259eaeb403a1c19850d74e9ed2663eeccb62397b24",
          "sha1": "9fa34b4fb67eafb8fd06ea7eeb3e009b2de4d9d4",
          "md5": "7ecf3460cdbb1c2339cfede2bef46467"
        }
      ]
    }
  ]
}
