{
  "formatVersion": "1.1",
  "component": {
    "group": "purplecreate.tramways",
    "module": "tramways-forge",
    "version": "0.3.0-mc1.20.1-forge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tramways-forge-0.3.0-mc1.20.1-forge.jar",
          "url": "tramways-forge-0.3.0-mc1.20.1-forge.jar",
          "size": 810148,
          "sha512": "cf08ea94a6f57d6298f7415815d5b4a6ec10e5fe7e711adabf75ec71f552180f6602a3525bc5593bcf1e747164b30ca40e64795d13a1d895d4bc5bb4d93b1f9a",
          "sha256": "f338f7d9efb9924d9c7d8de63e58750c240beddc20c0132a1e38c5d21532e90d",
          "sha1": "0574790beca684e278e5935bc7e8866c8413bbd3",
          "md5": "26383b2d64915031a5bb5823b6c58fb3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "0.3.5"
          }
        },
        {
          "group": "javazoom",
          "module": "jlayer",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.simibubi.create",
          "module": "create-1.20.1",
          "version": {
            "requires": "6.0.6-150"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "create-1.20.1",
              "type": "jar",
              "extension": "jar",
              "classifier": "slim"
            }
          }
        },
        {
          "group": "com.tterrag.registrate",
          "module": "Registrate",
          "version": {
            "requires": "MC1.20-1.3.3"
          }
        },
        {
          "group": "net.createmod.ponder",
          "module": "Ponder-Forge-1.20.1",
          "version": {
            "requires": "1.0.80"
          }
        },
        {
          "group": "dev.engine-room.flywheel",
          "module": "flywheel-forge-1.20.1",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "tramways-forge-0.3.0-mc1.20.1-forge.jar",
          "url": "tramways-forge-0.3.0-mc1.20.1-forge.jar",
          "size": 810148,
          "sha512": "cf08ea94a6f57d6298f7415815d5b4a6ec10e5fe7e711adabf75ec71f552180f6602a3525bc5593bcf1e747164b30ca40e64795d13a1d895d4bc5bb4d93b1f9a",
          "sha256": "f338f7d9efb9924d9c7d8de63e58750c240beddc20c0132a1e38c5d21532e90d",
          "sha1": "0574790beca684e278e5935bc7e8866c8413bbd3",
          "md5": "26383b2d64915031a5bb5823b6c58fb3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tramways-forge-0.3.0-mc1.20.1-forge-sources.jar",
          "url": "tramways-forge-0.3.0-mc1.20.1-forge-sources.jar",
          "size": 396832,
          "sha512": "f59de1d3a51f88e80e9cfc0005ac3650d5ff4f5e791242b89aacb0bf8eba3fed9d6590da963c642a65e3ce07bd2af47a4fc758d1b7e13e8f3c198ddad83ce538",
          "sha256": "2f0cfb74c6467ddb8bd85e47875d4c54de2413f51337afe4986c312c3b9d2ecb",
          "sha1": "876a8c888c78da0d52bde8666c7d51ec593cc339",
          "md5": "2612318e4b04de459e244e14bed591bd"
        }
      ]
    }
  ]
}
